name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VERSION: 4.10.1
  
jobs:

  build-and-push:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
     - name: Log in to the Container registry
       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
       with:
         registry: ${{ env.REGISTRY }}
         username: ${{ github.actor }}
         password: ${{ secrets.GH_TOKEN }}
         
     - uses: actions/checkout@v3
     - name: Build and tag image     
       run: docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
     - name: Push image to registry with version tag
       run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
     - name: Push image to registry with tag latest
       run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
